image:
  file: .gitpod.dockerfile

tasks:
- before: |
    export PATH=$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$ANDROID_HOME/platform-tools:$PATH
    mkdir -p /home/gitpod/.android
    touch /home/gitpod/.android/repositories.cfg
    brew install build-essential libkrb5-dev gcc make gradle openjdk-8-jdk
  command: |
    echo "Installing Flutter SDK..."
    cd /sdk && wget -qO flutter_sdk.tar.xz https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.12.13+hotfix.7-stable.tar.xz && tar -xf flutter_sdk.tar.xz && rm -f flutter_sdk.tar.xz
    echo "Installing Android SDK..."
    mkdir -p /sdk/android-sdk && cd /sdk/android-sdk && wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && unzip sdk-tools-linux-4333796.zip && rm -f sdk-tools-linux-4333796.zip
    /sdk/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
    echo "Init Flutter..."
    cd /workspace/ha_client
    flutter upgrade
    flutter doctor --android-licenses
    flutter pub get
    echo "Ready to go!"
    flutter doctor
vscode:
  extensions:
    - Dart-Code.dart-code@3.5.0-beta.1:Wg2nTABftVR/Dry4tqeY1w==
    - Dart-Code.flutter@3.5.0:/kOacEWdiDRLyN/idUiM4A==
