name: hass_client
description: Home Assistant Android Client

version: 0.7.5+750


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: any
  shared_preferences: any
  progress_indicators: any
  event_bus: any
  cached_network_image: any
  url_launcher: any
  date_format: any
  charts_flutter: ^0.8.1
  flutter_markdown: 0.3.0
  in_app_purchase: ^0.2.1+4
  flutter_custom_tabs: ^0.6.0
  firebase_messaging: ^5.1.6
  uni_links: ^0.2.0
  flutter_secure_storage: ^3.3.1+1
  device_info: ^0.4.0+3
  flutter_local_notifications: ^0.8.4
  geolocator: ^5.1.5
  workmanager: ^0.1.3
  battery: ^0.3.1+1
  sentry: ^2.3.1
  share:
    git:
      url: https://github.com/d-silveira/flutter-share.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: false
  image_path: "images/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - images/hassio-192x192.png
    - assets/js/externalAuth.js

  fonts:
    - family: "Material Design Icons"
      fonts:
        - asset: fonts/materialdesignicons-webfont-4.5.95.ttf
