name: hass_client
description: Home Assistant Android Client

version: 1.3.0+1303


environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.1.0
  shared_preferences: ^0.5.6+1
  path_provider: ^1.6.5
  event_bus: ^1.1.1
  cached_network_image: ^2.3.0-beta
  url_launcher: ^5.4.1
  date_format: ^1.0.8
  charts_flutter: ^0.8.1
  flutter_markdown: ^0.3.3
  in_app_purchase: ^0.3.4
  flutter_custom_tabs: ^0.6.0
  flutter_webview_plugin: ^0.3.10+1
  webview_flutter: ^0.3.19+7
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  device_info: ^0.4.2+4
  firebase_crashlytics: ^0.1.3+3
  syncfusion_flutter_core: ^18.2.44
  syncfusion_flutter_gauges: ^18.2.44
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/js/externalAuth.js
    - assets/html/cameraView.html
    - assets/html/cameraLiveView.html

  fonts:
    - family: "Material Design Icons"
      fonts:
        - asset: fonts/materialdesignicons-webfont-5.3.45.ttf
