name: hass_client
description: Home Assistant Android Client

version: 0.7.7+770


environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.1.0
  shared_preferences: ^0.5.6+1
  progress_indicators: ^0.1.4
  event_bus: ^1.1.1
  cached_network_image: ^2.0.0
  url_launcher: ^5.4.1
  date_format: ^1.0.8
  charts_flutter: ^0.8.1
  flutter_markdown: ^0.3.3
  in_app_purchase: ^0.3.0+3
  flutter_custom_tabs: ^0.6.0
  flutter_webview_plugin: ^0.3.10+1
  firebase_messaging: ^6.0.9
  flutter_secure_storage: ^3.3.1+1
  device_info: ^0.4.1+4
  flutter_local_notifications: ^1.1.6
  geolocator: ^5.2.1
  workmanager: ^0.2.0
  battery: ^0.3.1+7
  firebase_crashlytics: ^0.1.2+5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: any

flutter_icons:
  android: true
  ios: false
  image_path: "images/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - images/hassio-192x192.png
    - assets/js/externalAuth.js

  fonts:
    - family: "Material Design Icons"
      fonts:
        - asset: fonts/materialdesignicons-webfont-4.5.95.ttf
